name: Documentation

on:
    push:
        branches: ["main"]
        paths-ignore:
            - ".gitignore"
            - "README.md"
            - ".github/workflows/wasm.yml"
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

env:
    CARGO_TERM_COLOR: always

jobs:
    build-docs:
        runs-on: ubuntu-latest
        env:
            RUSTDOCFLAGS: -D warnings
        steps:
            - uses: actions/checkout@v4
            - uses: actions/cache@v4
              with:
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      target
                  key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
            - run: cargo doc --release --no-deps --document-private-items
            - run: |
                  mkdir -p pages/docs
                  cp -r target/doc/. pages/docs/
            - uses: actions/upload-pages-artifact@v4
              with:
                  path: pages
            - id: deployment
              uses: actions/deploy-pages@v4
