name: WASM Sandbox

on:
    workflow_run:
        workflows: ["CI"]
        types: [completed]

env:
    CARGO_TERM_COLOR: always
    EMSDK_VERSION: 6.0.10 # req: >=6.0.10
    WASM_BINDGEN_CLI_VERSION: 0.2.129 # req: >=0.2.129
    # note: wasm-bindgen-cli must have the same version as the wasm-bindgen crate in Cargo.toml

jobs:
    build:
        if: github.event.workflow_run.conclusion == 'success'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
              with:
                  ref: ${{ github.event.workflow_run.head_sha }}
            - uses: actions/cache@v6
              with:
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      ~/.cargo/bin
                      ~/.cargo/.crates.toml
                      ~/.cargo/.crates2.json
                      target
                  key: ${{ runner.os }}-wasm-cargo-v1-${{ env.EMSDK_VERSION }}-${{ env.WASM_BINDGEN_CLI_VERSION }}-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml', '.cargo/config.toml') }}
            - uses: emscripten-core/setup-emsdk@v15
              with:
                  version: ${{ env.EMSDK_VERSION }}
                  actions-cache-folder: "emsdk-cache"
            - run: rustup target add wasm32-unknown-emscripten
            - run: cargo install wasm-bindgen-cli --version $WASM_BINDGEN_CLI_VERSION
            - env:
                  CFLAGS: -fwasm-exceptions
                  CXXFLAGS: -fwasm-exceptions
              run: cargo build-sandbox-wasm --verbose
            - name: Check build artifacts
              run: |
                  test -s target/wasm32-unknown-emscripten/release/deps/sandbox_wasm.js
                  test -s target/wasm32-unknown-emscripten/release/deps/sandbox_wasm.wasm
                  test -s target/wasm32-unknown-emscripten/release/sandbox_wasm.wasm
            - uses: actions/upload-artifact@v7
              with:
                  name: sandbox-wasm
                  if-no-files-found: error
                  path: |
                      target/wasm32-unknown-emscripten/release/deps/sandbox_wasm.js
                      target/wasm32-unknown-emscripten/release/deps/sandbox_wasm.wasm
                      target/wasm32-unknown-emscripten/release/sandbox_wasm.wasm
