name: Emscripten WASM

on:
    push:
        branches: ["main"]
        paths-ignore:
            - ".gitignore"
            - "README.md"
    pull_request:
    workflow_dispatch:

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: emscripten-core/setup-emsdk@v15
              with:
                  version: 6.0.10 # req: >=6.0.10
                  actions-cache-folder: "emsdk-cache"
            - run: rustup target add wasm32-unknown-emscripten
            # wasm-bindgen-cli must be installed with the version pinned in Cargo.toml
            - run: cargo install wasm-bindgen-cli --version 0.2.129
            - env:
                  CFLAGS: -fwasm-exceptions
                  CXXFLAGS: -fwasm-exceptions
              run: cargo build-sandbox-wasm --verbose
            - name: Check build artifacts
              run: |
                  test -s target/wasm32-unknown-emscripten/release/deps/sandbox_wasm.js
                  test -s target/wasm32-unknown-emscripten/release/deps/sandbox_wasm.wasm
                  test -s target/wasm32-unknown-emscripten/release/sandbox_wasm.wasm
            - uses: actions/upload-artifact@v4
              with:
                  name: sandbox-wasm
                  if-no-files-found: error
                  path: |
                      target/wasm32-unknown-emscripten/release/deps/sandbox_wasm.js
                      target/wasm32-unknown-emscripten/release/deps/sandbox_wasm.wasm
                      target/wasm32-unknown-emscripten/release/sandbox_wasm.wasm
